version: "3.8"
services:
    # PHP Service
    php:
        container_name: asn-app
        build:
            context: .
            target: php
            args:
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
            - CONTAINER_ROLE=app
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - 8800:8800
        depends_on:
            - asn-db
        networks:
            - asn-net

    # Database Server
    asn-db:
        container_name: asn-db
        image: mysql:8.0
        ports:
            - 3310:3310
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - TZ=Asia/Shanghai
        volumes:
            - db-data:/var/lib/mysql
        networks:
            - asn-net

        # PHPmyAdmin
    phpmyadmin:
        image: phpmyadmin:5.2.0-apache
        container_name: asn-phpmyadmin
        restart: unless-stopped
        tty: true
        ports:
            - 8101:80
        networks:
            - asn-net
        environment:
            - PMA_ARBITRARY=1
            - UPLOAD_LIMIT=10000M

networks:
    asn-net:
        driver: bridge

volumes:
    db-data: ~
